spring.application.name=Application
server.port=8081

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:admin123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

project.image=images/
spring.sql.init.mode=always

spring.app.jwtSecret=${JWT_SECRET:mySecretKey123ShopKartApplicationABCDEFGHIJKLMNOPQRSTUVWXYZ}
spring.app.jwtExpirationMs=86400000
spring.app.jwtCookie=springBootEcommerce

#logging.level.com.Shopkart.Application.security=DEBUG